{"name": "Тест на проверку деления с числами внутри диапазона integer", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается -2, получено -1\nassert -1 == -2\n  --1\n  +-2", "trace": "setup = None, param_test = ({'left_operand': 496922891, 'operation': '/', 'right_operand': -166487298}, -2.9847495693034793)\n\n    @allure.feature(\"Тестирование функции калькулятора - деление\")\n    @allure.title(\"Тест на проверку деления с числами внутри диапазона integer\")\n    def test_division_for_integers_within_borders(setup, param_test):\n        (input_data, expected_data) = param_test\n        with allure.step(f\"отправляем запрос с входными данными {input_data} и получаем результат расчёта\"):\n            result = do_request_and_get_response(input_data)\n        expected_result = int(expected_data)\n        with allure.step(\"Проверяем, что полученный результат = ожидаемому\"):\n>           assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\nE           AssertionError: Ожидается -2, получено -1\nE           assert -1 == -2\nE             --1\nE             +-2\n\nexpected_data = -2.9847495693034793\nexpected_result = -2\ninput_data = {'left_operand': 496922891, 'operation': '/', 'right_operand': -166487298}\nparam_test = ({'left_operand': 496922891, 'operation': '/', 'right_operand': -166487298}, -2.9847495693034793)\nresult     = -1\nsetup      = None\n\ntests\\test_division.py:13: AssertionError"}, "steps": [{"name": "отправляем запрос с входными данными {'left_operand': 496922891, 'operation': '/', 'right_operand': -166487298} и получаем результат расчёта", "status": "passed", "start": 1579356539766, "stop": 1579356539952}, {"name": "Проверяем, что полученный результат = ожидаемому", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается -2, получено -1\nassert -1 == -2\n  --1\n  +-2\n", "trace": "  File \"C:\\Users\\Leonid\\PycharmProjects\\ModulBank\\tests\\test_division.py\", line 13, in test_division_for_integers_within_borders\n    assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\n"}, "start": 1579356539952, "stop": 1579356539953}], "parameters": [{"name": "param_test", "value": "({'left_operand': 496922891, 'operation': '/', 'right_operand': -166487298}, -2.9847495693034793)"}], "start": 1579356539765, "stop": 1579356539954, "uuid": "4551b42b-bdb2-4c8f-9c4e-82f0e264ad26", "historyId": "462ba8c07503a4f8df8889e3ff198f6e", "testCaseId": "9f6ca8f533d02c3e239a5a6be76bb0f5", "fullName": "tests.test_division#test_division_for_integers_within_borders", "labels": [{"name": "feature", "value": "Тестирование функции калькулятора - деление"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_division"}, {"name": "host", "value": "DESKTOP-1R5TURF"}, {"name": "thread", "value": "3512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_division"}]}