{"name": "test_division_for_integers_within_borders[all_negative_operands]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 2, получено -1\nassert -1 == 2\n  --1\n  +2", "trace": "setup = None, param_test = ({'left_operand': -2019208278, 'operation': '/', 'right_operand': -922832853}, 2)\n\n    @allure.suite(\"Тестирование калькулятора\")\n    @allure.feature(\"Тестирование функции калькулятора - деление\")\n    # @allure.title(\"Тест на проверку деления с числами внутри диапазона integer\")\n    def test_division_for_integers_within_borders(setup, param_test):\n        (input_data, expected_data) = param_test\n        with allure.step(f\"отправляем запрос с входными данными {input_data} и получаем результат расчёта\"):\n            result = do_request_and_get_response(input_data)\n        expected_result = expected_data\n        with allure.step(\"Проверяем, что полученный результат = ожидаемому\"):\n>           assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\nE           AssertionError: Ожидается 2, получено -1\nE           assert -1 == 2\nE             --1\nE             +2\n\nexpected_data = 2\nexpected_result = 2\ninput_data = {'left_operand': -2019208278, 'operation': '/', 'right_operand': -922832853}\nparam_test = ({'left_operand': -2019208278, 'operation': '/', 'right_operand': -922832853}, 2)\nresult     = -1\nsetup      = None\n\ntests\\test_division.py:14: AssertionError"}, "steps": [{"name": "отправляем запрос с входными данными {'left_operand': -2019208278, 'operation': '/', 'right_operand': -922832853} и получаем результат расчёта", "status": "passed", "start": 1579357577479, "stop": 1579357577664}, {"name": "Проверяем, что полученный результат = ожидаемому", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 2, получено -1\nassert -1 == 2\n  --1\n  +2\n", "trace": "  File \"C:\\Users\\Leonid\\PycharmProjects\\ModulBank\\tests\\test_division.py\", line 14, in test_division_for_integers_within_borders\n    assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\n"}, "start": 1579357577665, "stop": 1579357577666}], "parameters": [{"name": "param_test", "value": "({'left_operand': -2019208278, 'operation': '/', 'right_operand': -922832853}, 2)"}], "start": 1579357577479, "stop": 1579357577667, "uuid": "dc09468d-ea4f-45e7-ab76-d79bedb57c8e", "historyId": "a455d1b77f32359f44fd79db59d7e22b", "testCaseId": "9f6ca8f533d02c3e239a5a6be76bb0f5", "fullName": "tests.test_division#test_division_for_integers_within_borders", "labels": [{"name": "feature", "value": "Тестирование функции калькулятора - деление"}, {"name": "suite", "value": "Тестирование калькулятора"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-1R5TURF"}, {"name": "thread", "value": "4568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_division"}]}